export interface DemoCategorySeed {
  slug: string;
  name: string;
  description: string;
  parentSlug?: string;
}

/** Exact public taxonomy from master prompt §18. Extra groups are nested, never roots. */
export const demoCategories: readonly DemoCategorySeed[] = [
  {
    slug: 'ingredients',
    name: 'Ингредиенты',
    description: 'Профессиональные ингредиенты для кондитерского производства.',
  },
  {
    slug: 'chocolate-cocoa',
    name: 'Шоколад и какао',
    description: 'Кувертюр, шоколад и какао-продукты.',
  },
  {
    slug: 'dairy',
    name: 'Сливки, сыр и масло',
    description: 'Молочные продукты профессиональной фасовки.',
  },
  {
    slug: 'fruit-purees',
    name: 'Фруктовые и ягодные пюре',
    description: 'Пюре и фруктовое сырьё для кондитерских изделий.',
  },
  {
    slug: 'colors-flavors',
    name: 'Красители и ароматизаторы',
    description: 'Пищевые красители, экстракты и ароматизаторы.',
  },
  { slug: 'decor', name: 'Декор', description: 'Профессиональный декор для кондитерских изделий.' },
  {
    slug: 'molds',
    name: 'Формы и молды',
    description: 'Силиконовые, поликарбонатные и металлические формы.',
  },
  {
    slug: 'tools',
    name: 'Инвентарь и инструменты',
    description: 'Профессиональный кондитерский инвентарь.',
  },
  {
    slug: 'packaging',
    name: 'Упаковка',
    description: 'Коробки, подложки и транспортная упаковка.',
  },
  {
    slug: 'food-printing',
    name: 'Пищевая печать',
    description: 'Материалы для пищевой печати и переноса изображений.',
  },
  {
    slug: 'frozen',
    name: 'Замороженная продукция',
    description: 'Замороженные профессиональные заготовки.',
  },
  { slug: 'sale', name: 'Акции', description: 'Демонстрационные товары со сниженной ценой.' },
  { slug: 'new', name: 'Новинки', description: 'Новые позиции демонстрационного каталога.' },

  {
    slug: 'gelatin',
    parentSlug: 'ingredients',
    name: 'Желатин',
    description: 'Профессиональный желатин разной силы.',
  },
  {
    slug: 'agar',
    parentSlug: 'ingredients',
    name: 'Агар-агар',
    description: 'Агар для желе, начинок и декора.',
  },
  {
    slug: 'pectin',
    parentSlug: 'ingredients',
    name: 'Пектин',
    description: 'Пектины для глазурей, конфитюров и мармелада.',
  },
  {
    slug: 'starch',
    parentSlug: 'ingredients',
    name: 'Крахмал',
    description: 'Нативные и модифицированные крахмалы.',
  },
  {
    slug: 'thickeners',
    parentSlug: 'ingredients',
    name: 'Загустители',
    description: 'Стабилизаторы и загустители.',
  },
  {
    slug: 'albumin',
    parentSlug: 'ingredients',
    name: 'Альбумин',
    description: 'Сухой яичный белок для профессионального применения.',
  },
  {
    slug: 'powdered-sugar',
    parentSlug: 'ingredients',
    name: 'Сахарная пудра',
    description: 'Пудра разного помола и назначения.',
  },
  {
    slug: 'isomalt',
    parentSlug: 'ingredients',
    name: 'Изомальт',
    description: 'Изомальт для карамельного декора.',
  },
  {
    slug: 'syrups',
    parentSlug: 'ingredients',
    name: 'Сиропы',
    description: 'Глюкозный, инвертный и другие сиропы.',
  },
  {
    slug: 'nut-pastes',
    parentSlug: 'ingredients',
    name: 'Ореховые пасты',
    description: 'Пасты, пралине и ореховое сырьё.',
  },
  {
    slug: 'fillings',
    parentSlug: 'ingredients',
    name: 'Начинки',
    description: 'Термостабильные начинки и пралине.',
  },
  {
    slug: 'freeze-dried-berries',
    parentSlug: 'ingredients',
    name: 'Сублимированные ягоды',
    description: 'Ягоды и фруктовые порошки.',
  },
  {
    slug: 'fondant',
    parentSlug: 'ingredients',
    name: 'Мастика',
    description: 'Мастика для покрытия и моделирования.',
  },
  {
    slug: 'baking-mixes',
    parentSlug: 'ingredients',
    name: 'Смеси для выпечки',
    description: 'Профессиональные сухие смеси.',
  },

  {
    slug: 'chocolate-couverture',
    parentSlug: 'chocolate-cocoa',
    name: 'Кувертюр',
    description: 'Шоколад в профессиональной фасовке.',
  },
  {
    slug: 'cocoa-products',
    parentSlug: 'chocolate-cocoa',
    name: 'Какао-продукты',
    description: 'Какао-порошок, масло и тёртое какао.',
  },
  {
    slug: 'glazes-fillings',
    parentSlug: 'fillings',
    name: 'Глазури и готовые начинки',
    description: 'Глазури и готовые начинки.',
  },
  {
    slug: 'dairy-cream',
    parentSlug: 'dairy',
    name: 'Сливки и сухие молочные продукты',
    description: 'Сливки и молочные ингредиенты.',
  },
  {
    slug: 'nuts-pastes',
    parentSlug: 'nut-pastes',
    name: 'Орехи, пасты и пралине',
    description: 'Ореховое сырьё и пралине.',
  },
  {
    slug: 'fruits-purees',
    parentSlug: 'fruit-purees',
    name: 'Пюре и фруктовое сырьё',
    description: 'Фруктовые и ягодные пюре.',
  },
  {
    slug: 'food-colors',
    parentSlug: 'colors-flavors',
    name: 'Красители',
    description: 'Водо- и жирорастворимые красители.',
  },
  {
    slug: 'flavors',
    parentSlug: 'colors-flavors',
    name: 'Ароматизаторы',
    description: 'Ароматизаторы и экстракты.',
  },
  {
    slug: 'gelling-thickeners',
    parentSlug: 'ingredients',
    name: 'Желирующие и загустители',
    description: 'Желирующие агенты и стабилизаторы.',
  },
  {
    slug: 'sugars-syrups',
    parentSlug: 'ingredients',
    name: 'Сахара и сиропы',
    description: 'Специальные сахара и сиропы.',
  },
  {
    slug: 'equipment',
    parentSlug: 'tools',
    name: 'Оборудование',
    description: 'Оборудование для кондитерского цеха.',
  },
  {
    slug: 'bases-capsules',
    parentSlug: 'packaging',
    name: 'Подложки и капсулы',
    description: 'Подложки и капсулы.',
  },
  {
    slug: 'ice-cream',
    parentSlug: 'ingredients',
    name: 'Всё для мороженого',
    description: 'Сырьё для мороженого.',
  },
  {
    slug: 'hygiene',
    parentSlug: 'tools',
    name: 'Гигиена производства',
    description: 'Гигиенические расходные материалы.',
  },
  {
    slug: 'storage-transport',
    parentSlug: 'packaging',
    name: 'Хранение и транспортировка',
    description: 'Пищевые контейнеры.',
  },
  {
    slug: 'books-training',
    parentSlug: 'tools',
    name: 'Книги и обучение',
    description: 'Профессиональная литература.',
  },
  {
    slug: 'business-supplies',
    parentSlug: 'packaging',
    name: 'Оснащение бизнеса',
    description: 'Маркировка и вспомогательные материалы.',
  },
] as const;

export const demoBrands = [
  'Callebaut',
  'Cacao Barry',
  'Sosa Ingredients',
  'Irca',
  'Ravifruit',
  'AmeriColor',
  'Pavoni Italia',
  'Martellato',
  'Silikomart Professional',
  'Hochland Professional',
] as const;

export interface DemoProductSeed {
  name: string;
  category: string;
  brand: number;
  pack: string;
  price: number;
  form: string;
  purpose: string;
  country?: string;
}

export const demoProducts: readonly DemoProductSeed[] = [
  {
    name: 'Шоколад тёмный профессиональный 54,5%',
    category: 'chocolate-couverture',
    brand: 0,
    pack: '2,5 кг',
    price: 4390,
    form: 'Каллеты',
    purpose: 'Корпусные конфеты и ганаш',
    country: 'Бельгия',
  },
  {
    name: 'Шоколад тёмный профессиональный 70%',
    category: 'chocolate-couverture',
    brand: 1,
    pack: '1 кг',
    price: 2680,
    form: 'Пистоли',
    purpose: 'Плитки и декор',
    country: 'Франция',
  },
  {
    name: 'Шоколад молочный профессиональный 33,6%',
    category: 'chocolate-couverture',
    brand: 0,
    pack: '2,5 кг',
    price: 4520,
    form: 'Каллеты',
    purpose: 'Ганаш и муссы',
    country: 'Бельгия',
  },
  {
    name: 'Шоколад белый профессиональный 28%',
    category: 'chocolate-couverture',
    brand: 0,
    pack: '2,5 кг',
    price: 4690,
    form: 'Каллеты',
    purpose: 'Муссы и глазирование',
    country: 'Бельгия',
  },
  {
    name: 'Шоколад карамельный кувертюр',
    category: 'chocolate-couverture',
    brand: 3,
    pack: '1 кг',
    price: 2490,
    form: 'Диски',
    purpose: 'Конфеты и кремы',
    country: 'Италия',
  },
  {
    name: 'Шоколад рубиновый кувертюр',
    category: 'chocolate-couverture',
    brand: 0,
    pack: '1 кг',
    price: 2890,
    form: 'Каллеты',
    purpose: 'Декор и плитки',
    country: 'Бельгия',
  },
  {
    name: 'Шоколад без добавленного сахара тёмный',
    category: 'chocolate-couverture',
    brand: 3,
    pack: '1 кг',
    price: 2760,
    form: 'Диски',
    purpose: 'Специализированные десерты',
    country: 'Италия',
  },
  {
    name: 'Шоколад белый с пониженной текучестью',
    category: 'chocolate-couverture',
    brand: 1,
    pack: '1 кг',
    price: 2710,
    form: 'Пистоли',
    purpose: 'Декор и моделирование',
    country: 'Франция',
  },
  {
    name: 'Какао-порошок алкализованный 22–24%',
    category: 'cocoa-products',
    brand: 1,
    pack: '1 кг',
    price: 1590,
    form: 'Порошок',
    purpose: 'Бисквиты и напитки',
    country: 'Франция',
  },
  {
    name: 'Какао-порошок натуральный 10–12%',
    category: 'cocoa-products',
    brand: 2,
    pack: '1 кг',
    price: 1310,
    form: 'Порошок',
    purpose: 'Выпечка и кремы',
    country: 'Испания',
  },
  {
    name: 'Масло какао дезодорированное',
    category: 'cocoa-products',
    brand: 0,
    pack: '1 кг',
    price: 3290,
    form: 'Каллеты',
    purpose: 'Шоколад и велюр',
    country: 'Бельгия',
  },
  {
    name: 'Какао тёртое натуральное',
    category: 'cocoa-products',
    brand: 1,
    pack: '1 кг',
    price: 2380,
    form: 'Кусочки',
    purpose: 'Bean-to-bar и ганаш',
    country: 'Франция',
  },
  {
    name: 'Глазурь зеркальная нейтральная',
    category: 'glazes-fillings',
    brand: 3,
    pack: '3 кг',
    price: 2170,
    form: 'Гель',
    purpose: 'Покрытие тортов',
    country: 'Италия',
  },
  {
    name: 'Глазурь шоколадная готовая',
    category: 'glazes-fillings',
    brand: 3,
    pack: '5 кг',
    price: 3540,
    form: 'Паста',
    purpose: 'Глазирование изделий',
    country: 'Италия',
  },
  {
    name: 'Начинка малиновая термостабильная',
    category: 'glazes-fillings',
    brand: 4,
    pack: '2 кг',
    price: 1960,
    form: 'Пюре с кусочками',
    purpose: 'Выпечка и прослойка',
    country: 'Франция',
  },
  {
    name: 'Начинка лимонная термостабильная',
    category: 'glazes-fillings',
    brand: 3,
    pack: '2 кг',
    price: 1820,
    form: 'Крем',
    purpose: 'Тарты и выпечка',
    country: 'Италия',
  },
  {
    name: 'Пралине хрустящее миндальное',
    category: 'glazes-fillings',
    brand: 1,
    pack: '1 кг',
    price: 2890,
    form: 'Паста',
    purpose: 'Конфеты и прослойки',
    country: 'Франция',
  },
  {
    name: 'Сливки кондитерские ультрапастеризованные 35%',
    category: 'dairy-cream',
    brand: 3,
    pack: '1 л',
    price: 760,
    form: 'Жидкость',
    purpose: 'Взбивание и ганаш',
    country: 'Италия',
  },
  {
    name: 'Сливки растительные для декора',
    category: 'dairy-cream',
    brand: 3,
    pack: '1 л',
    price: 590,
    form: 'Жидкость',
    purpose: 'Отсадка и покрытие',
    country: 'Италия',
  },
  {
    name: 'Молоко сухое обезжиренное',
    category: 'dairy-cream',
    brand: 2,
    pack: '1 кг',
    price: 890,
    form: 'Порошок',
    purpose: 'Шоколад и мороженое',
    country: 'Испания',
  },
  {
    name: 'Сыворотка молочная сухая',
    category: 'dairy-cream',
    brand: 2,
    pack: '1 кг',
    price: 720,
    form: 'Порошок',
    purpose: 'Мороженое и выпечка',
    country: 'Испания',
  },
  {
    name: 'Паста фисташковая 100%',
    category: 'nuts-pastes',
    brand: 2,
    pack: '1 кг',
    price: 5890,
    form: 'Паста',
    purpose: 'Кремы и джелато',
    country: 'Испания',
  },
  {
    name: 'Паста фундука 100%',
    category: 'nuts-pastes',
    brand: 2,
    pack: '1 кг',
    price: 3190,
    form: 'Паста',
    purpose: 'Пралине и ганаш',
    country: 'Испания',
  },
  {
    name: 'Миндальная мука мелкого помола',
    category: 'nuts-pastes',
    brand: 2,
    pack: '1 кг',
    price: 1490,
    form: 'Мука',
    purpose: 'Макарон и бисквиты',
    country: 'Испания',
  },
  {
    name: 'Пралине фундук 50%',
    category: 'nuts-pastes',
    brand: 1,
    pack: '1 кг',
    price: 2740,
    form: 'Паста',
    purpose: 'Конфеты и муссы',
    country: 'Франция',
  },
  {
    name: 'Пюре манго без сахара замороженное',
    category: 'fruits-purees',
    brand: 4,
    pack: '1 кг',
    price: 1390,
    form: 'Пюре',
    purpose: 'Муссы и сорбеты',
    country: 'Франция',
  },
  {
    name: 'Пюре малины без сахара замороженное',
    category: 'fruits-purees',
    brand: 4,
    pack: '1 кг',
    price: 1690,
    form: 'Пюре',
    purpose: 'Муссы и начинки',
    country: 'Франция',
  },
  {
    name: 'Пюре маракуйи без сахара замороженное',
    category: 'fruits-purees',
    brand: 4,
    pack: '1 кг',
    price: 1840,
    form: 'Пюре',
    purpose: 'Кремы и сорбеты',
    country: 'Франция',
  },
  {
    name: 'Цукаты апельсиновые кубик',
    category: 'fruits-purees',
    brand: 2,
    pack: '1 кг',
    price: 1430,
    form: 'Кубики',
    purpose: 'Кексы и конфеты',
    country: 'Испания',
  },
  {
    name: 'Краситель гелевый красный',
    category: 'food-colors',
    brand: 5,
    pack: '128 г',
    price: 980,
    form: 'Гель',
    purpose: 'Кремы и мастика',
    country: 'США',
  },
  {
    name: 'Краситель гелевый синий',
    category: 'food-colors',
    brand: 5,
    pack: '128 г',
    price: 980,
    form: 'Гель',
    purpose: 'Кремы и мастика',
    country: 'США',
  },
  {
    name: 'Краситель жирорастворимый жёлтый',
    category: 'food-colors',
    brand: 2,
    pack: '20 г',
    price: 620,
    form: 'Порошок',
    purpose: 'Шоколад и масло какао',
    country: 'Испания',
  },
  {
    name: 'Диоксид титана альтернативный белый краситель',
    category: 'food-colors',
    brand: 2,
    pack: '100 г',
    price: 840,
    form: 'Порошок',
    purpose: 'Глазури и декор',
    country: 'Испания',
  },
  {
    name: 'Экстракт ванили натуральный',
    category: 'flavors',
    brand: 2,
    pack: '500 мл',
    price: 2980,
    form: 'Жидкость',
    purpose: 'Кремы и выпечка',
    country: 'Испания',
  },
  {
    name: 'Ароматизатор фисташка',
    category: 'flavors',
    brand: 2,
    pack: '50 г',
    price: 890,
    form: 'Паста',
    purpose: 'Кремы и мороженое',
    country: 'Испания',
  },
  {
    name: 'Ароматизатор кофе концентрированный',
    category: 'flavors',
    brand: 3,
    pack: '100 г',
    price: 740,
    form: 'Паста',
    purpose: 'Муссы и ганаш',
    country: 'Италия',
  },
  {
    name: 'Пектин NH термообратимый',
    category: 'gelling-thickeners',
    brand: 2,
    pack: '500 г',
    price: 2490,
    form: 'Порошок',
    purpose: 'Глазури и конфитюр',
    country: 'Испания',
  },
  {
    name: 'Желатин говяжий 220 Bloom',
    category: 'gelling-thickeners',
    brand: 2,
    pack: '1 кг',
    price: 2780,
    form: 'Порошок',
    purpose: 'Муссы и желе',
    country: 'Испания',
  },
  {
    name: 'Агар-агар 900',
    category: 'gelling-thickeners',
    brand: 2,
    pack: '500 г',
    price: 1690,
    form: 'Порошок',
    purpose: 'Желе и начинки',
    country: 'Испания',
  },
  {
    name: 'Стабилизатор для мороженого',
    category: 'gelling-thickeners',
    brand: 2,
    pack: '500 г',
    price: 1890,
    form: 'Порошок',
    purpose: 'Джелато и сорбеты',
    country: 'Испания',
  },
  {
    name: 'Глюкозный сироп кондитерский',
    category: 'sugars-syrups',
    brand: 3,
    pack: '1 кг',
    price: 620,
    form: 'Сироп',
    purpose: 'Карамель и ганаш',
    country: 'Италия',
  },
  {
    name: 'Инвертный сахар',
    category: 'sugars-syrups',
    brand: 2,
    pack: '1,4 кг',
    price: 810,
    form: 'Сироп',
    purpose: 'Конфеты и выпечка',
    country: 'Испания',
  },
  {
    name: 'Декстроза моногидрат',
    category: 'sugars-syrups',
    brand: 2,
    pack: '1 кг',
    price: 540,
    form: 'Порошок',
    purpose: 'Мороженое и выпечка',
    country: 'Испания',
  },
  {
    name: 'Посыпка шоколадная хрустящая',
    category: 'decor',
    brand: 0,
    pack: '500 г',
    price: 930,
    form: 'Кранч',
    purpose: 'Декор десертов',
    country: 'Бельгия',
  },
  {
    name: 'Лист трансферный для шоколада геометрия',
    category: 'decor',
    brand: 7,
    pack: '10 листов',
    price: 1190,
    form: 'Листы',
    purpose: 'Декор шоколада',
    country: 'Италия',
  },
  {
    name: 'Пищевое золото хлопья',
    category: 'decor',
    brand: 2,
    pack: '1 г',
    price: 1490,
    form: 'Хлопья',
    purpose: 'Финишный декор',
    country: 'Испания',
  },
  {
    name: 'Форма силиконовая для муссовых пирожных',
    category: 'molds',
    brand: 8,
    pack: '1 шт',
    price: 2890,
    form: 'Силиконовая форма',
    purpose: 'Муссовые пирожные',
    country: 'Италия',
  },
  {
    name: 'Форма поликарбонатная для конфет сфера',
    category: 'molds',
    brand: 7,
    pack: '1 шт',
    price: 2390,
    form: 'Поликарбонатная форма',
    purpose: 'Корпусные конфеты',
    country: 'Италия',
  },
  {
    name: 'Кольцо кондитерское перфорированное 18 см',
    category: 'molds',
    brand: 6,
    pack: '1 шт',
    price: 980,
    form: 'Металлическое кольцо',
    purpose: 'Тарты и выпечка',
    country: 'Италия',
  },
  {
    name: 'Шпатель кондитерский изогнутый 25 см',
    category: 'tools',
    brand: 7,
    pack: '1 шт',
    price: 890,
    form: 'Инструмент',
    purpose: 'Выравнивание и декор',
    country: 'Италия',
  },
  {
    name: 'Мешки кондитерские одноразовые 55 см',
    category: 'tools',
    brand: 6,
    pack: '100 шт',
    price: 1590,
    form: 'Расходный материал',
    purpose: 'Отсадка крема',
    country: 'Италия',
  },
  {
    name: 'Аэрограф кондитерский профессиональный',
    category: 'equipment',
    brand: 7,
    pack: '1 комплект',
    price: 12900,
    form: 'Оборудование',
    purpose: 'Окрашивание и велюр',
    country: 'Италия',
  },
  {
    name: 'Коробка для торта 30×30×30 см',
    category: 'packaging',
    brand: 7,
    pack: '10 шт',
    price: 1290,
    form: 'Коробка',
    purpose: 'Упаковка торта',
    country: 'Россия',
  },
  {
    name: 'Коробка для 6 капкейков с окном',
    category: 'packaging',
    brand: 7,
    pack: '25 шт',
    price: 1690,
    form: 'Коробка',
    purpose: 'Упаковка капкейков',
    country: 'Россия',
  },
  {
    name: 'Подложка усиленная круглая 30 см',
    category: 'bases-capsules',
    brand: 7,
    pack: '10 шт',
    price: 890,
    form: 'Подложка',
    purpose: 'Сборка и перенос торта',
    country: 'Россия',
  },
  {
    name: 'Круассан сливочный замороженный',
    category: 'frozen',
    brand: 4,
    pack: '60 шт',
    price: 4890,
    form: 'Замороженная заготовка',
    purpose: 'Расстойка и выпечка',
    country: 'Франция',
  },
  {
    name: 'Смесь для мягкого мороженого ваниль',
    category: 'ice-cream',
    brand: 3,
    pack: '2 кг',
    price: 1780,
    form: 'Порошок',
    purpose: 'Мягкое мороженое',
    country: 'Италия',
  },
  {
    name: 'Перчатки нитриловые неопудренные',
    category: 'hygiene',
    brand: 7,
    pack: '100 шт',
    price: 790,
    form: 'Расходный материал',
    purpose: 'Гигиена производства',
    country: 'Малайзия',
  },
  {
    name: 'Контейнер пищевой герметичный 12 л',
    category: 'storage-transport',
    brand: 7,
    pack: '1 шт',
    price: 1490,
    form: 'Контейнер',
    purpose: 'Хранение ингредиентов',
    country: 'Италия',
  },
  {
    name: 'Книга «Технология шоколадных конфет»',
    category: 'books-training',
    brand: 1,
    pack: '1 шт',
    price: 3290,
    form: 'Книга',
    purpose: 'Профессиональное обучение',
    country: 'Россия',
  },
  {
    name: 'Этикетки термотрансферные 58×40 мм',
    category: 'business-supplies',
    brand: 7,
    pack: '700 шт',
    price: 640,
    form: 'Рулон',
    purpose: 'Маркировка продукции',
    country: 'Россия',
  },
  {
    name: 'Крахмал кукурузный модифицированный',
    category: 'starch',
    brand: 2,
    pack: '1 кг',
    price: 690,
    form: 'Порошок',
    purpose: 'Загущение начинок',
    country: 'Испания',
  },
  {
    name: 'Альбумин сухой яичный белок',
    category: 'albumin',
    brand: 2,
    pack: '500 г',
    price: 1790,
    form: 'Порошок',
    purpose: 'Безе и меренга',
    country: 'Испания',
  },
  {
    name: 'Сахарная пудра ультрамелкого помола',
    category: 'powdered-sugar',
    brand: 2,
    pack: '2 кг',
    price: 610,
    form: 'Порошок',
    purpose: 'Глазурь и крем',
    country: 'Россия',
  },
  {
    name: 'Изомальт кондитерский в гранулах',
    category: 'isomalt',
    brand: 2,
    pack: '1 кг',
    price: 990,
    form: 'Гранулы',
    purpose: 'Карамельный декор',
    country: 'Германия',
  },
  {
    name: 'Малина сублимированная кусочки',
    category: 'freeze-dried-berries',
    brand: 4,
    pack: '100 г',
    price: 1390,
    form: 'Кусочки',
    purpose: 'Декор и начинки',
    country: 'Франция',
  },
  {
    name: 'Мастика сахарная белая для покрытия',
    category: 'fondant',
    brand: 3,
    pack: '1 кг',
    price: 890,
    form: 'Паста',
    purpose: 'Покрытие и моделирование',
    country: 'Италия',
  },
  {
    name: 'Смесь сухая для шоколадного бисквита',
    category: 'baking-mixes',
    brand: 3,
    pack: '2 кг',
    price: 1290,
    form: 'Порошок',
    purpose: 'Профессиональная выпечка',
    country: 'Италия',
  },
  {
    name: 'Сыр сливочный Cremette Professional',
    category: 'dairy-cream',
    brand: 9,
    pack: '2 кг',
    price: 2190,
    form: 'Сливочный сыр',
    purpose: 'Кремы и чизкейки',
    country: 'Россия',
  },
  {
    name: 'Коробка для бенто-торта 16×16×10 см',
    category: 'packaging',
    brand: 7,
    pack: '25 шт',
    price: 1490,
    form: 'Коробка',
    purpose: 'Упаковка бенто-тортов',
    country: 'Россия',
  },
] as const;

export const demoSynonyms = [
  ['шоколадные капли', 'шоколад каллеты'],
  ['кондитерский шоколад', 'кувертюр'],
  ['какао порошок', 'какао-порошок'],
  ['желирующее', 'пектин'],
  ['загуститель', 'стабилизатор'],
  ['пищевой краситель', 'краситель'],
  ['ореховая паста', 'пралине'],
  ['фруктовое пюре', 'пюре'],
  ['мешок', 'кондитерские мешки'],
  ['форма конфет', 'поликарбонатная форма'],
  ['коробка торт', 'коробка для торта'],
  ['сливки кондитерские', 'сливки 35%'],
] as const;
